### ISSUE TITLE
How do you get the unit_type of RL unit?

### ISSUE THREAD

**Issue by liushunyu** [shariqiqbal2810/REFIL#2]
Hello, thanks for your excellent work.

I want to know how do you get the unit_type of RL unit?

e.g.
```
if utype == 1935:
        return 'Baneling_RL'
```
where do you define "1935" for "Baneling_RL"?

**Comment by shariqiqbal2810** [comment]
The `*_RL` units are customized unit types that are modified to not attack automatically when attacked (since they will be controlled by RL agents). I believe the unit IDs can be found by opening the map in the StarCraft II map editor.

**Comment by liushunyu** [comment]
Sorry to keep after you, but could you tell me how to find the unit IDs in the StarCraft II map editor.

I have searched the whole editor and didn't find this ID.

The most similar is the "#" column in "editor->data editor->unit tab", but the ID in "#" column cannot match the ID used in the environment.

Or can I get the unit ID by unit Name by any API? (pysc2 only provide the standard unit ID api but no new unit ID api)

Hope to receive your reply. Thank you!

**Comment by liushunyu** [comment]
Because I want run your code under the SC version 4.10 (not 4.6 used by your project), I find the used RL unit ID is wrong to match the correct unit.

**Comment by shariqiqbal2810** [comment]
Ah ok my mistake, it's not viewable in the editor. I actually managed to find some old notes on this. What you need to do is create a map with all the possible units already spawned, then observe all units in the map like [here](https://github.com/oxwhirl/smac/blob/master/smac/env/starcraft2/starcraft2.py#L1509). Then, you can iterate through and look at `unit.unit_type` (which is the ID), `unit.health`, and `unit.shield` and map those to the values that correspond to each unit (in the table below - columns are: unit name, health, shield, and ID). Basically we know how much health and shield each unit type is supposed to have, so we can observe them as well as the ID in the initialized units and use that to map IDs to names.

![image](https://user-images.githubusercontent.com/5599715/140548745-efcd3be9-c95d-4b65-8a35-46a3b3e35cf5.png)


The game will give the custom units IDs starting from some `min_value` up to `min_value + n_types - 1` where `n_types` is the number of custom units (i.e. the ones that end with `_RL`) that exist in the map file. Sorry for the really convoluted process, but this is the only way I could figure out to do it!

**Comment by liushunyu** [comment]
Thank you! I will try it!

**Comment by chaobiubiu** [comment]
Hello, thanks for your valuable suggestions about deploying this work to SC2.4.10. I have created an auxiliary map with all possible RL units and record their unit types. 

Accordingly I revise the starcraft2custom.py file. However, when I launch the custom smac env, it raise an exception: "pysc2.lib.remote_controller.RequestError: SC2APIProtocol.ResponseCreateGame.Error.InvalidMapData: 'temporary map '' has invalid data.'". I have tries some ways but failed to solve it. Can you give me some advices? Thank you!
