### ISSUE TITLE
requirement.txt not exist

### ISSUE THREAD

**Issue by Schopenhauer-loves-Hegel** [shariqiqbal2810/REFIL#3]
requirement.txt not exist
could you add a requirement.txt, thanks

**Comment by shariqiqbal2810** [comment]
This codebase assumes the use of Docker for running experiments. If you'd like, you can manually install the packages listed in the [Dockerfile](https://github.com/shariqiqbal2810/REFIL/blob/master/docker/Dockerfile) in a virtual environment, though we can't guarantee it will produce the same results.
